### PR TITLE
fix for is pro not installed

### LINKED ISSUE #294: [Bug]: Filament\Forms\ComponentContainer::Filament\Forms\Concerns\{closure}(): Argument #1 ($component) must be of type Filament\Forms\Components\Component, null given
### What happened?

I'm getting this error when editing/adding a form. It looks like it has to do with some Fields: 

Checkbox
DateTimePicker
Toggle
DatePicker
RichEditor
TimePicker
Textarea
Paragraph

and specific with the Bolt::hasPro()  true/false check --> null

so when i add a field "CheckBoxList" for example, then i receive the error: 
```
Filament\Forms\ComponentContainer::Filament\Forms\Concerns\{closure}(): Argument #1 ($component) must be of type Filament\Forms\Components\Component, null given
```

After digging some deeper i came out at the function:
```php
 public static function getOptionsHidden(): array
```
when i comment out the line:
```
Bolt::hasPro() ? \LaraZeus\BoltPro\Facades\GradeOptions::hidden() : null,
```

that part works and i won't get any error anymore.

So i tried using that return array to be with array_filter(). So that NULL values will be removed.
This helps.

I see a lot of places where Bolt::hasPro() is used and i think because maybe latest  filament update cannot handle the null values for the "field Options" in the dialog.

i'm using Filament version: v3.2.85

### How to reproduce the bug

update to latest filament and zeus-bolt. create a new form, and add a field with one of the types : 

Checkbox
DateTimePicker
Toggle
DatePicker
RichEditor
TimePicker
Textarea
Paragraph

### Package Version

3.0.46

### PHP Version

8.3.7

### Laravel Version

10.48.12

### Which operating systems does with happen with?

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by atmonshi**

### CODE REVIEW

**Comment by eelco2k** [comment]
I see now if not pro: an empty array item. But why not the array_filter() ? As it completely removes that item from the list. .. 
thank you for fast fix 👌🏻

**Comment by atmonshi** [comment]
🤔 can you explain how to use it with conditional array item?

...Bolt::hasPro() ? \LaraZeus\BoltPro\Facades\GradeOptions::schema($field) : [],

**Comment by eelco2k** [comment]
well i only meant it for this function:

```php
public static function getOptionsHidden(): array
    {
        return [
            // @phpstan-ignore-next-line
            Bolt::hasPro() ? \LaraZeus\BoltPro\Facades\GradeOptions::hidden() : null,
            self::hiddenDataSource(),
            self::hiddenVisibility(),
            self::hiddenHtmlID(),
            self::hiddenHintOptions(),
            self::hiddenRequired(),
            self::hiddenColumnSpanFull(),
        ];
    }
```
    
wrap the array with array_filter() function like so:
    
```php
public static function getOptionsHidden(): array
    {
        return array_filter([
            // @phpstan-ignore-next-line
            Bolt::hasPro() ? \LaraZeus\BoltPro\Facades\GradeOptions::hidden() : null,
            self::hiddenDataSource(),
            self::hiddenVisibility(),
            self::hiddenHtmlID(),
            self::hiddenHintOptions(),
            self::hiddenRequired(),
            self::hiddenColumnSpanFull(),
        ]);
    }
```

it will completely remove the null / empty array items, so you don't have an empty array item in the array which you return. Keeps the return array of getOptionsHidden() clean.

**Comment by atmonshi** [comment]
you're right, but instead of duplicate the `array_filter` on all classes I am already cleaning it up when been called [here](https://github.com/lara-zeus/bolt/blob/a15e1f18cdba84c1ac2086c48af666b8c73b9267/src/Concerns/Schemata.php#L484) :)

**Comment by eelco2k** [comment]
Ah didn't see that one in the commits. you already found a way. that's perfect!

**Pull request merged**
